version: "3.8"

services:

  mysql:
    container_name: mysql
    image: mysql:8.0.22
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tigerhallkittensdb
      MYSQL_USER: tigerhalluser
      MYSQL_PASSWORD: tigerhallpass
      MYSQL_ROOT_PASSWORD: secret
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      start_period: 20s
